### PR TITLE
migrate to 19 Tooth Foundation banner ad, due to their generous support

### PR DESCRIPTION
**Pull request by ChillyRelleno**

### CODE REVIEW

**Review by ChillyRelleno — COMMENTED** [review]
Simply flawless.

**Comment by sshirokov** [comment]
It would be nice if it picked one of the banners at random

**Comment by ChillyRelleno** [comment]
It would be nice if it did that. But it's Christmas.

**Comment by SolientArt** [comment]
I agree with @sshirokov though just to make things difficult I'd suggest the 19 banner show up more often than the ATC banner.

**Comment by ChillyRelleno** [comment]
@sshirokov skalnik says it works

**Comment by skalnik** [comment]
> @sshirokov skalnik says it works

This is libel

**Comment by ChillyRelleno** [comment]
image

**Comment by ChillyRelleno** [comment]
I simply have that thing where you read backwards

**Pull request merged**
